backend/lab_4/cidei/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cidei.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'app.views.index', name='index'),
    url(r'^items/$', 'app.views.items', name='items'),
    url(r'^items/(?P<itm_id>\d+)/$', 'app.views.itemDetails', name='details-item'),
    url(r'^categorias/$', 'app.views.categorias', name='categorys'),
    #url(r'^categorias/(?P<cate_id>\d+)/$', 'app.views.categoryDetails', name='details-categorias'),
    url(r'^categorias/(?P<slug>[\w-]+)/$', 'app.views.categoryDetails', name='details-categorias'),
    url(r'^about/$', 'app.views.about', name='about'),
)

backend/lab_4/app/models.py
from django.db import models

# Create your models here.

L_TYPES = (
	('t', 'Todas'),
	('n', 'Ninguna'),
	('r', 'Resuelto'),
)

class Category(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, unique=True)

	def __unicode__(self):
		return "%s - %s" % (self.name, self.slug)

class Item(models.Model):
	listing = models.CharField(max_length=1, choices=L_TYPES, default='t')
	name = models.CharField(max_length=120)
	category = models.ForeignKey(Category)
	department = models.CharField(max_length=255)
	description = models.TextField()
	posted_on = models.DateTimeField(auto_now_add=True)
	update_item = models.DateTimeField()

	def __unicode__(self):
		return "%s - %s - %s - %s - %s" % (self.name, self.category, self.department, self.description, self.update_item)

class Picture(models.Model):
	item = models.ForeignKey(Item)
	url = models.CharField(max_length=255)

backend/lab_4/app/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import Context
from app.models import Category, Item
# Create your views here.

def index(request):
	context = Context({'title': 'Ejercicio lab 4 - Index'})
	return render_to_response('index.html', context)

def about(request):

	context = Context({'title': 'Ejercicio lab 4 - About', 'paragaph' : 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'})
	return render_to_response('about.html', context)

def items(request):
	items = Item.objects.all()
	context = Context({'title': 'Ejercicio lab 4 - Items' , 'item' : items})
	return render_to_response('items.html', context)

def categorias(request):
	categorias = Category.objects.all()
	context = Context({'title': 'Ejercicio lab 4 - Categorias', 'categoria' : categorias})
	return render_to_response('categorias.html', context)

def itemDetails(request, itm_id):
	item = get_object_or_404(Item, id=itm_id)
	context = Context({
		'title' : 'Detalle de %s' % item.name,
		'item'  : item
 	})
 	return render_to_response('detailsItems.html', context)
 
#def categoryDetails(request, cate_id):
#	category = get_object_or_404(Category, id=cate_id)
def categoryDetails(request, slug):
	category = get_object_or_404(Category, slug=slug)	
	context = Context({
		'title' : 'Detalle de %s' % category.name,
		'category'  : category
 	})
 	return render_to_response('detailsCategory.html', context)

	

backend/lab_4/templates/about.html
<!DOCTYPE html>
<html>
	<head>
		<title> {{title}} </title>
	<head>
	<body>
		<p> <strong> {{title}} </strong> </p>
		<div>
			<p> {{paragaph}} </p>
		</div>

	</body>
</html>

backend/lab_4/templates/categorias.html
<!DOCTYPE html>
<html>
	<head>
		<title> {{title}} </title>
	<head>
	<body>
		<p> <strong> {{title}} </strong> </p>

		<div>
		<p> <strong> Categorias </strong> </p>

			{% for cate in categoria %}
		 		<!--li> <a href=" {{ cate.id }} "> {{ cate.name|capfirst }} </a> </li-->
		 		<li> <a href=" {{ cate.slug }} "> {{ cate.name|capfirst }} </a> </li>
			{% endfor %}
		</div>

	</body>
</html>

backend/lab_4/templates/detailsCategory.html
<!DOCTYPE html>
<html>
	<head>
		<title> {{title}} </title>
	<head>
	<body>
		<h1> <strong> {{title}} </strong> </h1>
		
		<div>
			<ul> 
				<li> <b>Nombre</b> : {{category.name}} </li>
				<li> <b>Slug</b> : {{category.slug}} </li>
			</ul>

		</div>


	</body>
</html>

backend/lab_4/templates/detailsItems.html
<!DOCTYPE html>
<html>
	<head>
		<title> {{title}} </title>
	<head>
	<body>
		<h1> <strong> {{title}} </strong> </h1>
		
		<div>
			<ul> 
				<li> Nombre : {{item.name}} </li>
				<li> Categoria : {{item.category.name}} </li>
				<li> Listado : {{item.get_listing_display}} </li>
				<li> Departamento : {{item.department}} </li>
				<li> Creado : {{item.posted_on|date}} </li>
				<li> Modificado : {{item.update_item|date}} </li>

			</ul>
			<h2> Descripcion</h2>
			<p> {{item.description|linebreaksbr}} </p>
		</div>


	</body>
</html>

backend/lab_4/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<title> {{title}} </title>
	<head>
	<body>
		<p> <strong> {{title}} </strong> </p>
		<div>
			<ul>
				<li> <a href="items"> Items </a> </li>
				<li> <a href="categorias"> Categorias </a> </li>
				<li> <a href="about"> About </a> </li>
			</ul>
		</div>
	</body>
</html>

backend/lab_4/templates/items.html
<!DOCTYPE html>
<html>
	<head>
		<title> {{title}} </title>
	<head>
	<body>
		<p> <strong> {{title}} </strong> </p>

		<p> <strong> Items </strong> </p>
		<div>
			{% for itm in item %}
			 	<li> <a href="{{itm.id}}"> {{itm.name|capfirst}} </a> </li>
			{% endfor %}
		</div>

	</body>
</html>